% File generated by src/prolog_reasoning.py. Do not edit manually.

gioco(hades_like, rpg, 24.99, 30, 8, 0, 120000, 88).
gioco(short_puzzle_deluxe, puzzle, 34.99, 4, 6, 0, 60000, 72).
gioco(underlocalized_action, action, 19.99, 9, 1, 1, 90000, 81).
gioco(overpriced_multiplayer_rpg, rpg, 49.99, 8, 5, 1, 180000, 55).

predizione_commerciale(hades_like, cluster_0).
predizione_commerciale(short_puzzle_deluxe, cluster_2).
predizione_commerciale(underlocalized_action, cluster_0).
predizione_commerciale(overpriced_multiplayer_rpg, cluster_1).

rischio_bayesiano(hades_like, basso).
rischio_bayesiano(short_puzzle_deluxe, medio).
rischio_bayesiano(underlocalized_action, basso).
rischio_bayesiano(overpriced_multiplayer_rpg, alto).
