"""Python-Prolog integration for publisher funding decisions."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from config import PROLOG_DECISIONS_PATH, PROLOG_FACTS_PATH, PROLOG_RULES_PATH


DEMO_GAMES = [
    {
        "name": "hades_like",
        "genre": "rpg",
        "price": 24.99,
        "hours": 30,
        "languages": 8,
        "multiplayer": 0,
        "budget": 120000,
        "review_score": 88,
        "cluster": "cluster_0",
        "risk": "basso",
    },
    {
        "name": "short_puzzle_deluxe",
        "genre": "puzzle",
        "price": 34.99,
        "hours": 4,
        "languages": 6,
        "multiplayer": 0,
        "budget": 60000,
        "review_score": 72,
        "cluster": "cluster_2",
        "risk": "medio",
    },
    {
        "name": "underlocalized_action",
        "genre": "action",
        "price": 19.99,
        "hours": 9,
        "languages": 1,
        "multiplayer": 1,
        "budget": 90000,
        "review_score": 81,
        "cluster": "cluster_0",
        "risk": "basso",
    },
    {
        "name": "overpriced_multiplayer_rpg",
        "genre": "rpg",
        "price": 49.99,
        "hours": 8,
        "languages": 5,
        "multiplayer": 1,
        "budget": 180000,
        "review_score": 55,
        "cluster": "cluster_1",
        "risk": "alto",
    },
]


def generate_prolog_facts(games: list[dict] = DEMO_GAMES) -> Path:
    """Generate ordered Prolog facts from structured game records."""
    facts_path = Path(PROLOG_FACTS_PATH)
    facts_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "% File generated by src/prolog_reasoning.py. Do not edit manually.",
        "",
    ]

    for game in games:
        lines.append(
            "gioco("
            f"{game['name']}, "
            f"{game['genre']}, "
            f"{game['price']}, "
            f"{game['hours']}, "
            f"{game['languages']}, "
            f"{game['multiplayer']}, "
            f"{game['budget']}, "
            f"{game['review_score']}"
            ")."
        )

    lines.append("")
    for game in games:
        lines.append(f"predizione_commerciale({game['name']}, {game['cluster']}).")

    lines.append("")
    for game in games:
        lines.append(f"rischio_bayesiano({game['name']}, {game['risk']}).")

    facts_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return facts_path


def import_pyswip():
    """Import PySwip lazily because it also requires SWI-Prolog installed."""
    try:
        from pyswip import Prolog
    except ImportError as exc:
        raise ModuleNotFoundError(
            "Missing pyswip dependency. Install requirements.txt and SWI-Prolog before running this script."
        ) from exc
    return Prolog


def consult_knowledge_base():
    """Load Prolog rules and generated facts."""
    Prolog = import_pyswip()
    prolog = Prolog()

    rules_path = Path(PROLOG_RULES_PATH).resolve()
    facts_path = Path(PROLOG_FACTS_PATH).resolve()

    if not rules_path.exists():
        raise FileNotFoundError(f"Missing Prolog rules file: {rules_path}")
    if not facts_path.exists():
        raise FileNotFoundError(f"Missing Prolog facts file: {facts_path}")

    prolog.consult(str(rules_path))
    prolog.consult(str(facts_path))
    return prolog


def query_single_value(prolog, query: str, variable: str) -> str | None:
    """Return the first binding for a Prolog query."""
    results = list(prolog.query(query))
    if not results:
        return None
    return str(results[0][variable])


def query_all_values(prolog, query: str, variable: str) -> list[str]:
    """Return all bindings for a Prolog query."""
    return [str(row[variable]) for row in prolog.query(query)]


def unique_preserving_order(values: list[str]) -> list[str]:
    """Remove duplicates without changing Prolog result order."""
    seen = set()
    unique_values = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        unique_values.append(value)
    return unique_values


def build_decision_rows(prolog) -> list[dict]:
    """Query verdicts and blocking violations for every known game."""
    game_names = query_all_values(prolog, "gioco(Nome, _, _, _, _, _, _, _)", "Nome")
    rows = []

    for game in game_names:
        verdict = query_single_value(prolog, f"verdetto({game}, Verdetto)", "Verdetto")
        violations = query_all_values(
            prolog,
            f"violazione_bloccante({game}, Motivo)",
            "Motivo",
        )
        violations = unique_preserving_order(violations)

        rows.append(
            {
                "Game": game,
                "Verdict": verdict or "nessun_verdetto",
                "Approved": bool(list(prolog.query(f"approva_finanziamento({game})"))),
                "Needs_Review": bool(list(prolog.query(f"richiede_revisione({game})"))),
                "Rejected": bool(list(prolog.query(f"rifiuta_finanziamento({game})"))),
                "Blocking_Violations": ";".join(violations),
            }
        )

    return rows


def run_prolog_reasoning() -> pd.DataFrame:
    """Run Prolog reasoning and save the decision table."""
    generate_prolog_facts()
    prolog = consult_knowledge_base()
    decisions_df = pd.DataFrame(build_decision_rows(prolog))
    Path(PROLOG_DECISIONS_PATH).parent.mkdir(parents=True, exist_ok=True)
    decisions_df.to_csv(PROLOG_DECISIONS_PATH, index=False)
    return decisions_df


if __name__ == "__main__":
    decisions = run_prolog_reasoning()
    print(decisions.to_string(index=False))
